version: 2.1

aliases:
  - &docker-image
    docker:
      - image: docker
  - &setup-remote-docker
    setup_remote_docker:
      docker_layer_caching: true
  - &ignore-main
    filters:
      branches:
        ignore: main
  - &only-main
    filters:
      branches:
        only: main
  - &build-and-push
    run:
      name: "Docker  build and push"
      command: |
        IMAGE_NAME=eversc/go-pr-checks
        docker build -t $IMAGE_NAME:$DOCKER_IMAGE_TAG -f $DOCKERFILE_PATH .
        echo $DOCKER_PASS | docker login -u=$DOCKER_USER --password-stdin
        docker push $IMAGE_NAME:$DOCKER_IMAGE_TAG
  - &build
    run:
      name: "Docker  build"
      command: |
        IMAGE_NAME=eversc/go-pr-checks
        docker build -t $IMAGE_NAME:$DOCKER_IMAGE_TAG -f $DOCKERFILE_PATH .
        docker run -i $IMAGE_NAME:$DOCKER_IMAGE_TAG sh -c './test_cmds.sh'
  - &dockerfile-path-1-13
    environment:
      - DOCKERFILE_PATH: docker/Dockerfile_1_13
      - DOCKER_IMAGE_TAG: 1.13
  - &dockerfile-path-1-14
    environment:
      - DOCKERFILE_PATH: docker/Dockerfile_1_14
      - DOCKER_IMAGE_TAG: 1.14
  - &dockerfile-path-1-15
    environment:
      - DOCKERFILE_PATH: docker/Dockerfile_1_15
      - DOCKER_IMAGE_TAG: 1.15
  - &dockerfile-path-1-16
    environment:
      - DOCKERFILE_PATH: docker/Dockerfile_1_16
      - DOCKER_IMAGE_TAG: 1.16
  - &dockerfile-path-1-17
    environment:
      - DOCKERFILE_PATH: docker/Dockerfile_1_17
      - DOCKER_IMAGE_TAG: 1.17
  - &dockerfile-path-1-18
    environment:
      - DOCKERFILE_PATH: docker/Dockerfile_1_18
      - DOCKER_IMAGE_TAG: 1.17
  - &dockerfile-path-latest
    environment:
      - DOCKERFILE_PATH: docker/Dockerfile_1_18
      - DOCKER_IMAGE_TAG: latest

jobs:
  docker_build_1_13:
    <<: *docker-image
    <<: *dockerfile-path-1-13
    steps:
      - checkout
      - <<: *setup-remote-docker
      - <<: *build
  docker_build_and_push_1_13:
    <<: *docker-image
    <<: *dockerfile-path-1-13
    steps:
      - checkout
      - <<: *setup-remote-docker
      - <<: *build-and-push
  docker_build_1_14:
    <<: *docker-image
    <<: *dockerfile-path-1-14
    steps:
      - checkout
      - <<: *setup-remote-docker
      - <<: *build
  docker_build_and_push_1_14:
    <<: *docker-image
    <<: *dockerfile-path-1-14
    steps:
      - checkout
      - <<: *setup-remote-docker
      - <<: *build-and-push
  docker_build_1_15:
    <<: *docker-image
    <<: *dockerfile-path-1-15
    steps:
      - checkout
      - <<: *setup-remote-docker
      - <<: *build
  docker_build_and_push_1_15:
    <<: *docker-image
    <<: *dockerfile-path-1-15
    steps:
      - checkout
      - <<: *setup-remote-docker
      - <<: *build-and-push
  docker_build_1_16:
    <<: *docker-image
    <<: *dockerfile-path-1-16
    steps:
      - checkout
      - <<: *setup-remote-docker
      - <<: *build
  docker_build_and_push_1_16:
    <<: *docker-image
    <<: *dockerfile-path-1-16
    steps:
      - checkout
      - <<: *setup-remote-docker
      - <<: *build-and-push
  docker_build_1_17:
    <<: *docker-image
    <<: *dockerfile-path-1-17
    steps:
      - checkout
      - <<: *setup-remote-docker
      - <<: *build
  docker_build_and_push_1_17:
    <<: *docker-image
    <<: *dockerfile-path-1-17
    steps:
      - checkout
      - <<: *setup-remote-docker
      - <<: *build-and-push
  docker_build_1_18:
    <<: *docker-image
    <<: *dockerfile-path-1-18
    steps:
      - checkout
      - <<: *setup-remote-docker
      - <<: *build
  docker_build_and_push_1_18:
    <<: *docker-image
    <<: *dockerfile-path-1-18
    steps:
      - checkout
      - <<: *setup-remote-docker
      - <<: *build-and-push
  docker_build_and_push_latest:
    <<: *docker-image
    <<: *dockerfile-path-latest
    steps:
      - checkout
      - <<: *setup-remote-docker
      - <<: *build-and-push

workflows:
  commit:
    jobs:
      - docker_build_1_13:
          <<: *ignore-main
      - docker_build_and_push_1_13:
          <<: *only-main
      - docker_build_1_14:
          <<: *ignore-main
      - docker_build_and_push_1_14:
          <<: *only-main
      - docker_build_1_15:
          <<: *ignore-main
      - docker_build_and_push_1_15:
          <<: *only-main
      - docker_build_1_16:
          <<: *ignore-main
      - docker_build_and_push_1_16:
          <<: *only-main
      - docker_build_1_17:
          <<: *ignore-main
      - docker_build_and_push_1_17:
          <<: *only-main
      - docker_build_1_18:
          <<: *ignore-main
      - docker_build_and_push_1_18:
          <<: *only-main
      - docker_build_and_push_latest:
          <<: *only-main
