FROM golang:1.20.11-alpine

RUN apk --no-cache add git openssh gcc musl-dev

RUN go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
RUN go install golang.org/x/lint/golint@latest

ENV PATH="${PATH}:/usr/local/go/bin"

COPY test_cmds.sh .
